Проектирование *Сервиса запросов информации* о наличии товаров на полках в режиме реального времени (*API* определения наличия товаров на полках) для региональной ритейловой компании "eDA".

*Название*: On-shelf Availability API : Real-Time Store Inventory Query Service.

Ссервис дает быстрые ответы "есть ли товар на полке" и "в каком магазине рядом" для клиентов и сотрудников магазинов или сервисов доставки с мобильными устройствами.

*Цель создания сервиса*: уменьшить отмены заказов и повысить конверсию.

Сервис предполагает высокую нагрузку:

- потоковые обновления остатков из PoS и Cистемы управления складом (WMS),
- конфликтующие источники истины,
- обработку пиковых значений запросов на наиболее популярные SKU.

В составе проекта представлены следующие артефакты:

    link:./architecture-decision.md[Архитектурное решение]
    link:./Отчет.md[Отчеты о выполнении ДЗ и проекта]

Используется формат описания AsciiDoc

Рендер в pdf:

[source, shell]
docker run --rm -v "$(pwd):/data" pandoc/latex:alpine
sh -c "find /data -name '*.md' | sort |
pandoc -f markdown -t pdf -o /data/Архитектурное_решение.pdf
--pdf-engine=xelatex --toc -V geometry:margin=2.5cm"
