=== 2.4. Интеграции

. *Кассовая система POS (Point of Sale)* -- Потоковая передача событий продаж, возвратов, аннулирований чеков. +
Система : внешняя для Сервиса, внутренняя для eDA. Поток данных: входящий (POS -> Сервис).
. *Складская система WMS (Warehouse Management)* -- Передача данных о пополнении полок, получение корректировок после инвентаризации. +
Система : внешняя для Сервиса, внутренняя для eDA. Поток данных: двунаправленный (WMS <--> Сервис).
. *Система заказов OMS (Order Management System)* -- Передача запросов на резервирование/освобождение остатков под заказы клиентов, получение подтверждение резерва или отказ. +
Система : внешняя для Сервиса, внутренняя для eDA. Поток данных: двунаправленный (OMS <--> Сервис).
. *Pricing/Promo Engine (PPE)* -- Триггер предзагрузки кэша перед стартом промо-акций (anticipated load). +
Внутренняя система. Входящий (PPE <- Сервис).
. *Enterprise Resource Planning (ERP)* -- Финансовая сводка остатков (end-of-day snapshots), мастер-данные товаров. +
Внешняя система. Исходящий (ERP -> Сервис).
. *Loyalty Platform (LP)* -- Персонализация поиска (приоритет магазинов по программе лояльности клиента). +
Внешняя система. Входящий (LP <- Сервис).
. *External Logistics Services (LS)* -- Информация о доступности для служб экспресс-доставки (Яндекс.Лавка, Delivery Club). +
Внешняя система. Исходящий (LS -> Сервис).
