=== 2.4. Интеграции

. *Кассовая система (POS)*. Потоковая передача событий продаж, возвратов, аннулирований чеков.
* Система внешняя для Сервиса, внутренняя для eDA 
* Входящий поток данных : Сервис <- POS
* Интеграция через Адаптер POS (через API-gateway).
. *Складская система (WMS)*. Передача данных о пополнении полок, получение корректировок после инвентаризации. 
* Система внешняя для Сервиса, внутренняя для eDA
* Двунаправленный поток данных: Сервис <--> WMS
* Интеграция через Адаптер WMS (через API-gateway).
. *Система заказов (OMS)*. Передача запросов на резервирование/освобождение остатков под заказы клиентов, получение подтверждение резерва или отказ.
* Система внешняя для Сервиса, внутренняя для eDA 
* Двунаправленный поток данных: Сервис <--> OMS
* Интеграция через Адаптер OMS (через API-gateway).
. *Движок цен и промо-акций (PPE)*. Передает триггер предзагрузки кэша перед стартом промо-акций (ожидаемая подгрузка).
* Система внешняя для Сервиса, внутренняя для eDA 
* Входящий поток данных : Сервис <- PPE
* Прямая интеграция без адаптера и API-gateway.


. *Enterprise Resource Planning (ERP)* -- Финансовая сводка остатков (end-of-day snapshots), мастер-данные товаров. +
Внешняя система. Исходящий (ERP -> Сервис).
. *Loyalty Platform (LP)* -- Персонализация поиска (приоритет магазинов по программе лояльности клиента). +
Внешняя система. Входящий (LP <- Сервис).
. *External Logistics Services (LS)* -- Информация о доступности для служб экспресс-доставки (Яндекс.Лавка, Delivery Club). +
Внешняя система. Исходящий (LS -> Сервис).
