=== 2.4. Внешние интеграции

. *Кассовая система (POS)*. Потоковая передача событий продаж, возвратов, аннулирований чеков.
* Система внешняя для Сервиса, внутренняя для eDA
* Входящий поток данных : Сервис <- POS
* Интеграция через Адаптер POS (через API-gateway).
. *Складская система (WMS)*. Передача данных о пополнении полок, получение корректировок после инвентаризации.
* Система внешняя для Сервиса, внутренняя для eDA
* Двунаправленный поток данных: Сервис <--> WMS
* Интеграция через Адаптер WMS (через API-gateway).
. *Система заказов (OMS)*. Передача запросов на резервирование/освобождение остатков под заказы клиентов, получение подтверждение резерва или отказ.
* Система внешняя для Сервиса, внутренняя для eDA
* Двунаправленный поток данных: Сервис <--> OMS
* Интеграция через Адаптер OMS (через API-gateway).
. *Движок цен и промо-акций (PPE)*. Передает триггер предзагрузки кэша перед стартом промо-акций (ожидаемая подгрузка).
* Система внешняя для Сервиса, внутренняя для eDA
* Входящий поток данных : Сервис <- PPE
* Прямая интеграция без адаптера и API-gateway.
. *ERP-система*. Передача мастер-данных товаров (справочники SKU), получение финансовой сводки остатков (остатик на конец дня).
* Система внешняя для Сервиса, внутренняя для eDA
* Входящий поток данных: Сервис <--> ERP
* Интеграция через Адаптер ERP (через API-gateway).
. *Платформа Лояльности (LP)*.  По запросу передает данные уровня лояльности, правила персонализации поиска (приоритет магазинов по программе лояльности клиента).
* Система внешняя для eDA
* Двунаправленный поток данных: Сервис <--> LP
* Интеграция через Клиента лояльности без API-gateway.
. *Службы доставки*. Передают запросы на проверку доступности товара для служб экспресс-доставки (Яндекс.Лавка, Delivery Club) и получают статус наличия (доступен/нет).
* Системы внешние для eDA
* Двунаправленный поток данных: Сервис <--> Службы доставки
* Интеграция через Адаптер служб доставки (через API-gateway).

тест
