
@startuml

skinparam shadowing false
skinparam componentStyle rectangle
skinparam linetype ortho

title Схема развертывания Сервиса

cloud "Пользователи и внешние системы" {
  actor "Клиентские приложения"
  actor "Внешние системы"
}

node "Контур внешнего доступа" {
  [API Gateway]
}

node "Контейнерная платформа" {

  node "Контур пользовательских сервисов" {
    [Сервисы обработки запросов]
    [Сервисы резервирования]
  }

  node "Контур обработки событий" {
    [Сервисы обработки событий]
    [Сервисы синхронизации]
  }

  node "Контур эксплуатации" {
    [Мониторинг и журналирование]
  }
}

node "Event Bus" {
  queue "Kafka"
}

database "Контур хранения данных" {
  [PostgreSQL]
  [MongoDB]
  [Redis]
  [S3]
}

"Клиентские приложения" --> [API Gateway]
"Внешние системы" --> [API Gateway]

[API Gateway] --> [Сервисы обработки запросов]
[Сервисы обработки запросов] --> [Сервисы резервирования]

[Сервисы резервирования] --> "Kafka"
[Сервисы обработки событий] --> "Kafka"

[Сервисы обработки запросов] --> [Redis]
[Сервисы обработки запросов] --> [MongoDB]
[Сервисы резервирования] --> [PostgreSQL]

@enduml
