@startuml inventory_event_diagram
title Схема события изменения остатка

entity "Событие изменения остатка" as InventoryEvent {
  * event_id : UUID
  --
  event_type : string
  event_version : integer
  correlation_id : UUID
  occurred_at : datetime
  source : string
  sku_id : UUID
  store_id : UUID
  available_qty : integer
  reserved_qty : integer
  quantity_delta : integer
  stock_version : integer
}

@enduml