@startuml reservation_cancelled_event_diagram
title Схема события отмены резерва

entity "Событие отмены резерва" as ReservationCancelledEvent {
  * event_id : UUID
  --
  event_type : string
  event_version : integer
  correlation_id : UUID
  occurred_at : datetime
  source : string
  reservation_id : UUID
  sku_id : UUID
  store_id : UUID
  released_qty : integer
  cancel_reason : string
  reservation_status : string
  reservation_version : integer
}

@enduml