@startuml schema_registry_diagram
title Схема версионирования событийных данных

entity "БД реестра схем" as SchemaRegistry {
  * schema_id : UUID
  --
  schema_name : string
  schema_version : integer
  schema_format : string
  compatibility_mode : string
  status : string
  created_at : datetime
}

entity "Событие Event Bus" as EventMessage {
  * event_id : UUID
  --
  event_type : string
  event_version : integer
  schema_id : UUID
  payload : avro
  occurred_at : datetime
}

SchemaRegistry ||--o{ EventMessage : определяет_схему

@enduml