@startuml materialized_view_diagram
title Материализованное представление модели чтения

entity "Материализованное представление" as MaterializedView {
  * view_id : UUID
  --
  sku_id : UUID
  stores_count : integer
  available_qty_total : integer
  updated_at : datetime
}

@enduml