@startuml reservation_diagram
title Схема хранения резервов

entity "Резерв" as Reservation {
  * reservation_id : UUID
  --
  sku_id : UUID
  store_id : UUID
  request_id : UUID
  reserved_qty : integer
  status : string
  created_at : datetime
  expires_at : datetime
  updated_at : datetime
  version : integer
}

@enduml